### ISSUE TITLE
Move to Docker organisation to map with image name?

### ISSUE THREAD

**Issue by bfirsh** [moxiegirl/whalesay#2]
It's a bit confusing that the image name is `docker/whalesay`, but the repo is `moxiegirl/whalesay`.

**Comment by thaJeztah** [comment]
SGTM, not sure how that's done though

**Comment by thaJeztah** [comment]
The repository was transferred, so guess this one can be closed :smile: (don't have permissions to do so) /cc @dmp42

**Comment by dmp42** [comment]
*confused* :)

**Comment by bfirsh** [comment]
🎉

**Comment by dmp42** [comment]
Ok, my brain is now working.

@thaJeztah you now have write.
Thanks @bfirsh for closing this.

**Comment by thaJeztah** [comment]
> Ok, my brain is now working.

:joy: great, and thanks!
